### ISSUE TITLE
make a new update with 24.10

### ISSUE THREAD

**Issue by lux778999** [RetroScaler/Bluereteo-PS1-2#6]
right now the most recent version from darthcloud is 24.10, make a new update for the blueretro mini with these new features

**Comment by RetroScaler** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    Ok, got it. friend. We will check it.Thanks for your feedback.Beat regards,RetroScaler
    
        
            
        
    
    
        
            
        
    
    
         
        
            
                        ***@***.***
            
        
     

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/14/2024 11:54
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              [RetroScaler/Blueretro-PS] make a new update with 24.10 (Issue #6)
        
      
    
  
  
right now the most recent version from darthcloud is 24.10, make a new update for the blueretro mini with these new features

**Comment by lux778999** [comment]
thank you very much

**Comment by RetroScaler** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    NEW Firmware (24.10) for PS2 blueretro https://github.com/RetroScaler/Blueretro-PS/releases/tag/v24.10 
    
        
            
        
    
    
        
            
        
    
    
         
        
            
                        ***@***.***
            
        
     

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/16/2024 12:24
        
      
      
        
         To 
        
        
         
          
            ***@***.******@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [RetroScaler/Blueretro-PS] make a new update with 24.10 (Issue #6)
        
      
    
  
  
    Ok, got it. friend. We will check it.Thanks for your feedback.Beat regards,RetroScaler
    
        
            
        
    
    
        
            
        
    
    
         
        
            
                        ***@***.***
            
        
     

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/14/2024 11:54
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              [RetroScaler/Blueretro-PS] make a new update with 24.10 (Issue #6)
        
      
    
  
  
right now the most recent version from darthcloud is 24.10, make a new update for the blueretro mini with these new features
