### ISSUE TITLE
issue: rumble 24.10

### ISSUE THREAD

**Issue by lux778999** [RetroScaler/Bluereteo-PS1-2#7]
the version 1.9.0 has rumble and it works perfect, for some reason rumble doesnt work on the update 24.10(everything else works perfect), even though i already activated that on the config page from blueretro.io, it would be cool if you checked that, i use a blueretro mini. thanks

**Comment by RetroScaler** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    Dear friend, Sorry for the problem you met. Please tell me the game controller you used and the name of game you played. We will check it.  Best regards,Retroscaler
    
        
            
        
    
    
        
            
        
    
    
         
        
            
                        ***@***.***
            
        
     

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/17/2024 08:47
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              [RetroScaler/Blueretro-PS] issue: rumble 24.10 (Issue #7)
        
      
    
  
  
the version 1.9.0 has rumble and it works perfect, for some reason rumble doesnt work on the update 24.10(everything else works perfect), even though i already activated that on the config page from blueretro.io, it would be cool if you checked that, i use a blueretro mini. thanks

**Comment by lux778999** [comment]
hi, the problem was with a dualshock 4 original and one fake, plus a ds3 fake one, the thing is that it seems that it doesnt have rumble on all the controllers, i tried dragon ball tenkaichi 3, need for speed undergroun 2 and most wanted, so it would be pretty cool if you tried it yourself to see its behavior, to install the update i used the software that says the manual, thank you beforehand

**Comment by RetroScaler** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    Ok，got it. friend. We will check it as soon as possible.I will give you a reply on the 21st or 22nd. Sorry for the inconvenience again.
    
        
            
        
    
    
        
            
        
    
    
         
        
            
                        ***@***.***
            
        
     

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/19/2024 11:20
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [RetroScaler/Blueretro-PS] issue: rumble 24.10 (Issue #7)
        
      
    
  
  
hi, the problem was with a dualshock 4 original and one fake, plus a ds3 fake one, the thing is that it seems that it doesnt have rumble on all the controllers, i tried dragon ball tenkaichi 3, need for speed undergroun 2 and most wanted, so it would be pretty cool if you tried it yourself to see its behavior, to install the update i used the software that says the manual

**Comment by lux778999** [comment]
dont worry, and thanks for the attention

**Comment by RetroScaler** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    Dear friend, Sorry to reply you so late. please use the new firmware I sent you here to update the ps2 blueretro. It had been tested. 
    
        
            
        
    
    
        
            
        
    
    
         
        
            
                        ***@***.***
            
        
     

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/19/2024 12:37
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [RetroScaler/Blueretro-PS] issue: rumble 24.10 (Issue #7)
        
      
    
  
  
dont worry, and thanks for the attention

**Comment by lux778999** [comment]
hi, i cant see the version that you sent me, did you sent it? or try giving me a link to download it so i can try it

**Comment by lux778999** [comment]
hi friend i cant see the firmware that you sent me, could yo do it again or send me a link?


> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } Dear friend, Sorry to reply you so late. please use the new firmware I sent you here to update the ps2 blueretro. It had been tested.  ***@***.***
> […](#)
> ---- Replied Message ---- From ***@***.***> Date 10/19/2024 12:37 To ***@***.***> Cc ***@***.***> , ***@***.***> Subject Re: [RetroScaler/Blueretro-PS] issue: rumble 24.10 (Issue #7) dont worry, and thanks for the attention —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by RetroScaler** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    Here, friend. Scroll down and take a look at the email content.
    
        
            
        
    
    
        
            
        
    
    
         
        
            
                        ***@***.***
            
        
     

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/24/2024 07:27
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [RetroScaler/Blueretro-PS] issue: rumble 24.10 (Issue #7)
        
      
    
  
  
hi friend i cant see the firmware that you sent me, could yo do it again or send me a link?

font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } Dear friend, Sorry to reply you so late. please use the new firmware I sent you here to update the ps2 blueretro. It had been tested.  @.***
…
---- Replied Message ---- From @.> Date 10/19/2024 12:37 To @.> Cc @.> , @.> Subject Re: [RetroScaler/Blueretro-PS] issue: rumble 24.10 (Issue #7) dont worry, and thanks for the attention —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.***>

**Comment by lux778999** [comment]
bro i swear, is not appearing to me, i dont know why, neither here on github or on gmail, i dont know the reason but the archive is not appearing,

> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } Here, friend. Scroll down and take a look at the email content. ***@***.***
> […](#)
> ---- Replied Message ---- From ***@***.***> Date 10/24/2024 07:27 To ***@***.***> Cc ***@***.***> , ***@***.***> Subject Re: [RetroScaler/Blueretro-PS] issue: rumble 24.10 (Issue #7) hi friend i cant see the firmware that you sent me, could yo do it again or send me a link? font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } Dear friend, Sorry to reply you so late. please use the new firmware I sent you here to update the ps2 blueretro. It had been tested.  @.*** … ---- Replied Message ---- From @.> Date 10/19/2024 12:37 To @.> Cc @.> , @.> Subject Re: [RetroScaler/Blueretro-PS] issue: rumble 24.10 (Issue #7) dont worry, and thanks for the attention —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.***> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by lux778999** [comment]
![Captura de pantalla 2024-10-25 012249](https://github.com/user-attachments/assets/d54f2cc7-8b93-45fb-8fc8-2c3362c3c03e)
this is how it appears to me

**Comment by lux778999** [comment]
![git](https://github.com/user-attachments/assets/04943a93-04ea-4b01-8a98-b9180654472d)
and like this on github

**Comment by lux778999** [comment]
or try sending it trough discord, in the blueretro section since i just entered


> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } Here, friend. Scroll down and take a look at the email content. ***@***.***
> […](#)
> ---- Replied Message ---- From ***@***.***> Date 10/24/2024 07:27 To ***@***.***> Cc ***@***.***> , ***@***.***> Subject Re: [RetroScaler/Blueretro-PS] issue: rumble 24.10 (Issue #7) hi friend i cant see the firmware that you sent me, could yo do it again or send me a link? font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } Dear friend, Sorry to reply you so late. please use the new firmware I sent you here to update the ps2 blueretro. It had been tested.  @.*** … ---- Replied Message ---- From @.> Date 10/19/2024 12:37 To @.> Cc @.> , @.> Subject Re: [RetroScaler/Blueretro-PS] issue: rumble 24.10 (Issue #7) dont worry, and thanks for the attention —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.***> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by RetroScaler** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    Please give me an email address. I will try it again. 
    
        
            
        
    
    
        
            
        
    
    
         
        
            
                        ***@***.***
            
        
     

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/25/2024 12:32
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [RetroScaler/Blueretro-PS] issue: rumble 24.10 (Issue #7)
        
      
    
  
  
or try sending it trough discord, in the blueretro section since i just entered

font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } Here, friend. Scroll down and take a look at the email content. @.***
…
---- Replied Message ---- From @.> Date 10/24/2024 07:27 To @.> Cc @.> , @.> Subject Re: [RetroScaler/Blueretro-PS] issue: rumble 24.10 (Issue #7) hi friend i cant see the firmware that you sent me, could yo do it again or send me a link? font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } Dear friend, Sorry to reply you so late. please use the new firmware I sent you here to update the ps2 blueretro. It had been tested.  @.*** … ---- Replied Message ---- From @.> Date 10/19/2024 12:37 To @.> Cc @.> , @.> Subject Re: [RetroScaler/Blueretro-PS] issue: rumble 24.10 (Issue #7) dont worry, and thanks for the attention —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.>

**Comment by lux778999** [comment]
This is my email: Lux778999@gmail.com



> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } Please give me an email address. I will try it again.  ***@***.***
> […](#)
> ---- Replied Message ---- From ***@***.***> Date 10/25/2024 12:32 To ***@***.***> Cc ***@***.***> , ***@***.***> Subject Re: [RetroScaler/Blueretro-PS] issue: rumble 24.10 (Issue #7) or try sending it trough discord, in the blueretro section since i just entered font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } Here, friend. Scroll down and take a look at the email content. @.*** … ---- Replied Message ---- From @.> Date 10/24/2024 07:27 To @.> Cc @.> , @.> Subject Re: [RetroScaler/Blueretro-PS] issue: rumble 24.10 (Issue #7) hi friend i cant see the firmware that you sent me, could yo do it again or send me a link? font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } Dear friend, Sorry to reply you so late. please use the new firmware I sent you here to update the ps2 blueretro. It had been tested.  @.*** … ---- Replied Message ---- From @.> Date 10/19/2024 12:37 To @.> Cc @.> , @.> Subject Re: [RetroScaler/Blueretro-PS] issue: rumble 24.10 (Issue #7) dont worry, and thanks for the attention —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by lux778999** [comment]
![Captura de pantalla 2024-10-25 133011](https://github.com/user-attachments/assets/7cfaffaa-b02a-4142-8829-c01a25a41b42)
i asked in discord and berry passed me this file"Retroscaler-Blueretro-PS1&PS2-24.10-Rumble"(i dont send it to you because git hub doesnt accept .bin archives, maybe thats the reason why i couldn't see the archive that you were sending me) the thing is that when i update the blueretro it says that is the snes firmware, as you can see on the pic that is with this response.(github doesnt accept .bin archives but does accept .zip)
here is the version that was sent to me
[Retroscaler-Blueretro-PS1&PS2-24.10-Rumble.zip](https://github.com/user-attachments/files/17528067/Retroscaler-Blueretro-PS1.PS2-24.10-Rumble.zip)

**Comment by lux778999** [comment]
this was already fixed
